create table en_word (
    en_word_id int8 generated by default as identity,
    description varchar(255),
    word varchar(255),
    ru_word_ru_word_id int8,
    primary key (en_word_id)
);

create table ru_word (
    ru_word_id int8 generated by default as identity,
    translate varchar(255),
    primary key (ru_word_id)
);

create table user_role (
    user_id int8 not null,
    roles varchar(255)
);

create table usr (
    id int8 generated by default as identity,
    active boolean,
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id)
);

alter table if exists en_word
    add constraint en_word_ru_word_fk
    foreign key (ru_word_ru_word_id) references ru_word;

alter table if exists user_role
    add constraint user_role_user_fk
    foreign key (user_id) references usr;